### ISSUE TITLE
希望增加一些功能

### ISSUE THREAD

**Issue by lebonnuit** [endday/all-search#1]
1. 可以设置默认的搜索界面（比如默认打开就是搜索图片）
2. 图片搜索引擎希望可以添加yandex

谢谢！

**Comment by endday** [comment]
1、默认的搜索界面，每次操作切换类型，我都有保存的，你意思是我还要加一个默认的情况是吗
2、没问题
另外，我想问问大家的想法。
我想把网址列表从这个项目中摘出去，每次加载都是从一个url或者接口去读取。
这个url可以是一个简单的github仓库中的一个文件，文件就是个json数据。
通过修改这个加载的url，这样就能实现简单的自定义了，不知道这样能否接受

**Comment by endday** [comment]
> 1. 可以设置默认的搜索界面（比如默认打开就是搜索图片）
> 2. 图片搜索引擎希望可以添加yandex
> 
> 谢谢！

1、默认的搜索界面，每次操作切换类型，我都有保存的，你意思是我还要加一个默认的情况是吗
2、没问题
另外，我想问问大家的想法。
我想把网址列表从这个项目中摘出去，每次加载都是从一个url或者接口去读取。
这个url可以是一个简单的github仓库中的一个文件，文件就是个json数据。
通过修改这个加载的url，这样就能实现简单的自定义了，不知道这样能否接受

**Comment by lebonnuit** [comment]
我觉得非常好！！不好意思这两天没上git一直没回复

**Comment by endday** [comment]
已经在做另一个方案了，自定义设置，这一周应该能放个版本出来
