### ISSUE TITLE
希望能增加个同步配置功能，这样在更换电脑后还能继续使用

### ISSUE THREAD

**Issue by allawsl** [endday/all-search#11]
比如像暴力猴那样可以上传到配置文件到谷歌网盘，在更换电脑后可以直接调用网盘配置文档

**Comment by endday** [comment]
调研了几天，这个功能需要用到后端的，我这边除非是提供接口，不然应该是没法做到自动上传了
不过我可以提供一个excel导出导入的功能，这个能满足你的需求吗
