### ISSUE TITLE
几个小建议

### ISSUE THREAD

**Issue by ricepeak** [endday/all-search#17]
简单体验了一下，发现几个问题
1.是不是有些搜索引擎跳转后不会再展示顶部栏
2.建议背景能有其他颜色可选
3.【默认第一个】建议可选开关
4.YouTube和bili顶部挡住了一些🤣，建议添加超时隐藏开关（这个提议是否违背设计初衷）

**Comment by endday** [comment]
感谢反馈哈
1、你跳转到哪个搜索引擎了，我看看是不是加载的漏掉了
2、这个可以，我尽快加
3、这个我没太懂，这个顺序其实可以修改的
4、我去改一下，可能油管和b站样式改了

**Comment by ricepeak** [comment]
（回复这么及时）
旧电脑（chrome89|分辨率也低），等下个月新笔记本到了再认真配置下用。
1.翻译的deepl（应该是不同搜索引擎的区别，不行就返回上一页再更换，这个没必要改）
3.偶尔会出现等待列表浮出（说不上来原因），我想通过点击让列表出现而非直接跳转第一个
4.YouTube确实挡住了，b站不用改（我用了bilibili evolved），（仍觉得超时隐藏开关一劳永逸）
![image](https://user-images.githubusercontent.com/50504651/119908651-abdee800-bf85-11eb-8f84-2127242a67dc.png)

**Comment by endday** [comment]
1. deepl这个可能我需要详细了解这个网站的路由跳转机制才能解决了
2. 背景色的我还在改，过几天可能放一个版本
3. 
- 列表出现延时问题可能是setTimeout被劫持了，我考虑换一个实现方式来做延时。
- 点击触发菜单的功能，这个我可以加一个菜单触发的方式的配置来实现，的确是个必要的功能
4. 
- 这几天都在解决youtube的加载问题，他使用了spf.js框架，跳过了histroy的所有事件，导致我无法监听路由的改变事件。为了youtube花了较多时间，在考虑要不要做轮询了去查url的改变了，感觉有点影响性能
- 超时隐藏开关的确可以，但是我已经做了现在这种，改了会被骂死啊

**Comment by ricepeak** [comment]
好的，多谢开发者🧐

**Comment by endday** [comment]
超时隐藏的交互应该是怎样的，你能不能详细讲讲具体设计

**Comment by ricepeak** [comment]
鼠标位置离开all-search栏区域多少秒以后，自动向上收起隐藏；当鼠标由下面移动到收起之前的区域，all-search栏再次出现。就像移动到分类底下的各搜索引擎出现一样。
抱歉不能给予代码层面的帮助，非计算机系的python目前计算器水平，学习时间少😜
