### ISSUE TITLE
安卓端适配问题

### ISSUE THREAD

**Issue by Khan2001** [endday/all-search#20]
作者你好，我在手机上使用kiwi浏览器，安装了暴力猴扩展使用该脚本，在手机浏览器的界面上，很多时候顶部都会有遮挡（例如：谷歌的搜索界面，百度翻译界面等）
我的建议在脚本产生的整个顶部横幅的最左侧加入一个隐藏的按钮，隐藏后通过一个悬浮的按钮再次显现，这样在安卓端的体验会比较好
希望能够得到您的关注与改善😃

**Comment by endday** [comment]
有道理啊，我下个版本加入移动端的判断和你说的这个隐藏功能吧

**Comment by endday** [comment]
有道理啊，我下个版本加入移动端的判断和你说的这个隐藏功能吧

**Comment by endday** [comment]
移动端的判断和滚动已经有了，后面会添加按钮隐藏功能

**Comment by Khan2001** [comment]
不行啊
在我下滑界面的时候，顶部横幅没有自动隐藏
![Uploading Screenshot_20210723_170339_com.kiwibrowser.browser.jpg…]()
