### ISSUE TITLE
大佬能否介绍页里添加一块兼容性描述以及网页缩放的支持

### ISSUE THREAD

**Issue by VirgilSone** [endday/all-search#21]
1. 这个跟SearchEngineJump感觉功能上差不多，UI更好看些，但是介绍上没看到对兼容的描述，不知道作者有没有考虑兼容性？
比如SearchEngineJump有提到对“AC-baidu:重定向优化百度搜狗谷歌搜索_去广告_favicon_双列”的兼容，以及对“网页限制解除”的兼容。
2. 另外工具栏不会随着网页缩放而适配，比如放大到一定程度，就会从最右边（或下边）的设置开始显示不出来，放的越大越多会显示不出来，这个问题不知道是否有可能解决？
3. 还有就是工具栏大小是否可以做成自定义？
![image](https://user-images.githubusercontent.com/86765657/124225907-cbe06900-db3a-11eb-9ae1-ebf1d31f1c0a.png)
![image](https://user-images.githubusercontent.com/86765657/124225969-e74b7400-db3a-11eb-87a0-4ab7cd50cc68.png)

**Comment by endday** [comment]
大佬说得有道理，我这的确没有考虑兼容性的问题，都是chrome浏览器跑，自娱自乐
1、和别的插件的冲突问题，我暂时没有遇到，ac的baidu脚本我也装了，也没有什么影响，如果有插件冲突，欢迎反馈。
其实大部分工作量都来自于不同网站的展示问题。
2、缩放导致的设置不展示，是我没考虑到的，后面会解决的
3、工具栏大小自定义，你指的是哪部分自定义，菜单大小还是整体工具栏的高度？具体交互细节是怎样的？

**Comment by VirgilSone** [comment]
> 大佬说得有道理，我这的确没有考虑兼容性的问题，都是chrome浏览器跑，自娱自乐
> 1、和别的插件的冲突问题，我暂时没有遇到，ac的baidu脚本我也装了，也没有什么影响，如果有插件冲突，欢迎反馈。
> 其实大部分工作量都来自于不同网站的展示问题。
> 2、缩放导致的设置不展示，是我没考虑到的，后面会解决的
> 3、工具栏大小自定义，你指的是哪部分自定义，菜单大小还是整体工具栏的高度？具体交互细节是怎样的？

1. 大佬可以在介绍页说明一下跟ac-baidu兼容。
2. 嗯嗯谢谢大佬
3. emm，具体的话就是，在设置界面加上整体工具栏高度然后对应的字体大小也按比例缩放，或者是设置字体大小然后对应工具栏高度按比例缩放，这两种都可以，但是估计第二种（设置字体大小）可能用起来更容易理解？
