### ISSUE TITLE
脚本失效的解决方法

### ISSUE THREAD

**Issue by endday** [endday/all-search#25]
脚本已被举报，举报理由为压缩代码，申诉不通过，被管理员删除了
下面的是cdn的链接，和npm最新版本同步
https://cdn.jsdelivr.net/npm/all-search/build/index.user.js

**Comment by wolfan** [comment]
我说怎么这几天没有了，还觉得那怪怪的。

**Comment by PandaFang** [comment]
之前被greasy fork 删掉代码是空的。不知道几天前为什么安装上了，但是仍然不显示，刚刚收到了更新，这说明确实是安装上了，但是还是不显示。脚本里面是有代码的。
