### ISSUE TITLE
Startpages网站适配请求

### ISSUE THREAD

**Issue by ricepeak** [endday/all-search#28]
https://www.startpage.com/sp/search

**Comment by endday** [comment]
研究了一下，没搞懂startpage的搜索请求如何传参的，参数如果不放在url，我真不知道要怎么传参了

**Comment by ricepeak** [comment]
我自己找到了，安卓端的startpage有😅pc端也能用。https://www.startpage.com/sp/search?query=%s

Jerry Zhang ***@***.***> 于2021年12月20日周一 21:55写道：

**Comment by endday** [comment]
https://cdn.jsdelivr.net/npm/all-search@1.1.9/build/index.user.js
已添加startpage
