### ISSUE TITLE
增加 fsou.cc 支持 & 图标经常加载不上

### ISSUE THREAD

**Issue by SylleoYr** [endday/all-search#29]
rt，希望增加 [fsou](https://fsou.cc/) 支持。另外就是有时候图标经常加载不出来，目测应该是国内网络问题。不知是否可以对图标资源进行 cdn，或希望能够增加一个设置以关闭加载图标。

**Comment by endday** [comment]
添加fsou的要求没问题，不过图标加载的问题，我需要想想有什么好的解决方案

**Comment by SylleoYr** [comment]
> 添加fsou的要求没问题，不过图标加载的问题，我需要想想有什么好的解决方案

不知道图标是不是存在仓库内，如果是的话可以使用 [jsdelivr][https://www.jsdelivr.com/] 的 CDN；字体图标的话也可以用这个加速。如果是实时在线加载的话可以看看国内有无相关服务。

**Comment by jjjyyyllll** [comment]
> 添加fsou的要求没问题，不过图标加载的问题，我需要想想有什么好的解决方案

用base64缓存图标呢

**Comment by ricepeak** [comment]
更新后图标能加载了真是太好看了，但还是有个别图标偶尔不显示

**Comment by endday** [comment]
加了图标缓存功能，使用了yandex的api获取favicon，后续问题继续优化
