### ISSUE TITLE
大佬会做拓展吗?

### ISSUE THREAD

**Issue by Noah1995** [endday/all-search#3]
能否用selection-search给添加侧边栏常驻界面...
我用蹩脚的翻译软件反馈过给作者很久了...不确定会不会添加...
https://github.com/Pitmairen/selection-search/issues/74

https://chrome.google.com/webstore/detail/searchbar/fjefgkhmchopegjeicnblodnidbammed
我目前用的是SearchBar...
这个有常驻...
但是UI没有侧边栏啊...(这个也反馈很久了应该不会添加)

下面主要几个亮点功能(selection-search也有这些功能.但是没有常驻栏)
1丶 (划词文字会直接捕捉)
2丶支持鼠标右键输入框自动查找搜索串添加(少部分网页无效)
3丶支持get和post
4丶可以划词后显示面板一次和快捷键永久常驻
5丶...

效果是类似遨游内置这样可以折叠...
UI好看一点的...

![【2020-05-22】【06∶19∶41】](https://user-images.githubusercontent.com/25548230/64728268-36ab5500-d50d-11e9-98ff-7afe8dd83307.gif)

**Comment by endday** [comment]
老哥， 你这个是要我加功能还是要我去改别人的代码啊

**Comment by Noah1995** [comment]
都可以啊...
但是我觉得改别人的会更好...
人家都很完善了...

**Comment by endday** [comment]
但是有个问题啊，我这样做出来的扩展是没有上架谷歌商店的，到时就只能通过github来更新了，还得自己去手动下载安装到浏览器里

**Comment by Noah1995** [comment]
不上架关系也不大吧...
git有提醒啊...

拓展和油猴不通吗?
你就把拓展移植到脚本不行吗?

**Comment by endday** [comment]
1、油猴脚本那个要控制体积，不然我就偷懒上ui库，不自己手写了
2、扩展就不一样，扩展是下载到本地的，对大小要求很低，我就可以直接上ui库
3、如果说移植，他们的扩展和我这个脚本理论上是不冲突的，两个都安装也可以吧，那就不需要移植了
4、你说的一些新功能，我看看有哪些可以加上去

**Comment by Noah1995** [comment]
![【2020-05-22】【12∶08∶12】](https://user-images.githubusercontent.com/25548230/82630349-ff0cb500-9c24-11ea-906a-bf360883db1c.jpg)

但我还是觉得拓展更好...
拓展还可以做成Tidy Sidebar这样侧边栏独立窗口呢...

**Comment by endday** [comment]
老哥，给我点时间考虑下，我不一定有空写

**Comment by Noah1995** [comment]
![5NF%4R1~ H@P8 %0MSAOQN](https://user-images.githubusercontent.com/25548230/82630592-b4d80380-9c25-11ea-9851-5935c7b88824.gif)
好吧...

**Comment by Noah1995** [comment]
![74188](https://user-images.githubusercontent.com/25548230/82773286-3ae98980-9e74-11ea-8802-812ca5cc2cba.gif)
https://www.landiannews.com/archives/74188.html
听说edge chrome要做侧边栏搜索啊...
目前还没有出预览...
不知道是不是自定义多引擎的..
