### ISSUE TITLE
希望可以增加按CTRL另起一个网页的功能

### ISSUE THREAD

**Issue by zt0408** [endday/all-search#31]

**Comment by endday** [comment]
鼠标中间点击可以打开新窗口的，如果这个不够，可以加你的这个需求

**Comment by zt0408** [comment]
> 鼠标中间点击可以打开新窗口的，如果这个不够，可以加你的这个需求

我发现鼠标中键本身有功能，跟打开新窗口有冲突

**Comment by endday** [comment]
> > 鼠标中间点击可以打开新窗口的，如果这个不够，可以加你的这个需求
> 
> 我发现鼠标中键本身有功能，跟打开新窗口有冲突

chrome的鼠标中键点击就是打开新窗口啊，本身的功能是什么，还是说你用的其他浏览器点击鼠标中键不是这样的

**Comment by zt0408** [comment]
> > > 鼠标中间点击可以打开新窗口的，如果这个不够，可以加你的这个需求
> > 
> > 
> > 我发现鼠标中键本身有功能，跟打开新窗口有冲突
> 
> chrome的鼠标中键点击就是打开新窗口啊，本身的功能是什么，还是说你用的其他浏览器点击鼠标中键不是这样的

我用的是edge浏览器，点击鼠标中键鼠标的图标会变，此时移动鼠标可以移动整个网页的上下位置

**Comment by endday** [comment]
> > > > 鼠标中间点击可以打开新窗口的，如果这个不够，可以加你的这个需求
> > > 
> > > 
> > > 我发现鼠标中键本身有功能，跟打开新窗口有冲突
> > 
> > 
> > chrome的鼠标中键点击就是打开新窗口啊，本身的功能是什么，还是说你用的其他浏览器点击鼠标中键不是这样的
> 
> 我用的是edge浏览器，点击鼠标中键鼠标的图标会变，此时移动鼠标可以移动整个网页的上下位置

好的，我明白了，是我没有直接用a标签来做列表的问题，导致默认中键事件有问题，下个版本就修复这个问题

**Comment by endday** [comment]
不好意思，还改了很多别的打包相关的代码，所以花时间更新了一个大版本
你说的中键触发了滚动的问题已经修复了

**Comment by oliver-zhq** [comment]
希望能加上CTRL新网页功能，中间被其它软件占用了。
