### ISSUE TITLE
将设置由文字改为图标

### ISSUE THREAD

**Issue by VirgilSone** [endday/all-search#37]
在分类较多的情况下，会有遮挡，可以考虑把设置改成一个图标比如齿轮，以减少空间占用
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/86765657/174465376-b4e5098b-5b2e-4fbf-9822-c9322adde123.png">

**Comment by endday** [comment]
内容是可以横向滚动的，但是要按住shift加滚轮，我试下改为不需要按shift，用滚轮触发，这样会不会好点
