### ISSUE TITLE
维基百科遮挡

### ISSUE THREAD

**Issue by VirgilSone** [endday/all-search#38]
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/86765657/174465892-53af9c16-bea5-4aca-83a8-cbb12b766639.png">
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/86765657/174465895-cc57045d-7eb7-415d-8934-450da7ebbc17.png">

**Comment by VirgilSone** [comment]
哎？这个问题已经好了？我试了一下还是这样额

**Comment by VirgilSone** [comment]
哦哦更新了一下可以了。感谢大佬！

**Comment by endday** [comment]
> 哦哦更新了一下可以了。感谢大佬！

客气了，感谢反馈
