### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by arpir** [endday/all-search#42]
1. 在Yandex中，工具条会被遮挡。
2. 竖向时，文字与图标同时显示，占据的空间太大，能够更简洁优雅些？
3. All Search 这个英文标志显得没有必要，或者说不够优雅（不具有功能性，但是分量十足，也不够优美）。
4. 数据不能够导入导出，虽然在油猴子中数据可以手动备份，但是如果在设置页中重新编辑，油猴子中的数据会被覆盖掉。

**Comment by endday** [comment]
1、2、3的问题我去看看，想想要怎么改

4的重新编辑是怎么样操作，能具体点吗

**Comment by arpir** [comment]
> 1. 在这个页面编辑之后会在脚本数据里生成一些字段![1](https://cdn.jsdelivr.net/gh/arpir/Pics@main/2022/08/06/1.png) ，所以如果我备份这些字段也就能够保存自定义的配置了？但是 https://endday.github.io/all-search/config/sites ，编辑页面无法读取这些数据，导致下次便捷的时候会再次向脚本-›数据中覆盖。

**Comment by arpir** [comment]
> 1、2、3的问题我去看看，想想要怎么改
> 
> 4的重新编辑是怎么样操作，能具体点吗

另外我发现在 Safari浏览器中用 Userscript 插件使用这个脚本的时候也存在着和问题1相似的问题，鼠标hover浮动被遮挡了![2szd3u](https://cdn.jsdelivr.net/gh/arpir/Pics@main/2022/08/06/2szd3u.png)。在

**Comment by endday** [comment]
> > 1. 在这个页面编辑之后会在脚本数据里生成一些字段![1](https://camo.githubusercontent.com/0037a3a2df43349a36896a17791c30267955175c6cf31eced89c62a0c4e3a81d/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f61727069722f50696373406d61696e2f323032322f30382f30362f312e706e67) ，所以如果我备份这些字段也就能够保存自定义的配置了？但是 https://endday.github.io/all-search/config/sites ，编辑页面无法读取这些数据，导致下次便捷的时候会再次向脚本-›数据中覆盖。

覆盖的情况我没复现啊

**Comment by endday** [comment]
> > 1、2、3的问题我去看看，想想要怎么改
> > 4的重新编辑是怎么样操作，能具体点吗
> 
> 另外我发现在 Safari浏览器中用 Userscript 插件使用这个脚本的时候也存在着和问题1相似的问题，鼠标hover浮动被遮挡了![2szd3u](https://camo.githubusercontent.com/2b794fb3458dd2e1a331ad1c0877150e6d92060f285fa8f615dfdadce3c46262/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f61727069722f50696373406d61696e2f323032322f30382f30362f32737a6433752e706e67)。在

这个我是真没办法测试了，没有mac系统可以测试
