### ISSUE TITLE
如何在不需要all search的网页添加白名单,比如百度云盘

### ISSUE THREAD

**Issue by dsh2595977663** [endday/all-search#52]
![image](https://user-images.githubusercontent.com/60806652/208078971-82a19447-0136-40ba-95dc-0aea4bea8306.png)

**Comment by endday** [comment]
> ![image](https://user-images.githubusercontent.com/60806652/208078971-82a19447-0136-40ba-95dc-0aea4bea8306.png)

好的，我看看咋回事，很快就修复

**Comment by endday** [comment]
已经修复了，我改成新版的百度网盘

**Comment by dsh2595977663** [comment]
已看到修复，谢谢作者。

**Comment by dsh2595977663** [comment]
请问能否旧版的百度网盘能否做到不遮挡？旧版的百度网盘还是存在遮挡问题
（因为新版百度网盘的页面不能做到根据文件名排序，我还是比较习惯旧版的百度网盘）
辛苦作者，谢谢

**Comment by endday** [comment]
> 

https://pan.baidu.com/disk/home?from=newversion&stayAtHome=true#/search?key=%s&vmode=list
你先把这个加进设置里，这是旧版的百度网盘的，我看已经没有遮挡了
后面我会修复下百度网盘的hash参数问题
