### ISSUE TITLE
希望左上角的搜索按钮可以直接显示百度或者谷歌

### ISSUE THREAD

**Issue by k650dg4d2** [endday/all-search#56]
比如当我当前在百度的时候，左上角的搜索按钮直接显示的就是谷歌，点一下就能到谷歌搜索。在谷歌页面的时候上面直接显示百度的按钮，点一下直接到百度页面。

**Comment by endday** [comment]
现在点击分类会切换该分类的第一条和第二条
例如，搜索分类的1是百度，2是谷歌
直接点击搜索分类
当前在百度，就会跳转谷歌
当前在谷歌，就会跳转百度

这样应该能满足你的要求
