### ISSUE TITLE
ddg\多吉等无显示工具栏。

### ISSUE THREAD

**Issue by wolfan** [endday/all-search#7]

**Comment by SylleoYr** [comment]
我在 Firefox 81 上使用多吉搜索时也遇到了该问题，我使用的脚本管理器是 [ViolentMonkdy-暴力猴](https://violentmonkey.github.io/)，我不确定其他脚本管理器是否也存在相同的问题。

看了一下脚本发现原因在 [`@include` (#L64)](https://github.com/endday/all-search/blob/8cde52f6aeb06f843a91f964b300da6685145c15/src/config/loadList.js#L64) 匹配多吉搜索时使用的正则表达式（`/^https?:\/\/www\.dogedoge\.com\/results\?q/i`）结尾是字母 `i`（忽略搜索关键字的大小写），但在 ViolentMonkey 的文档中关于 @include 的[说明](https://violentmonkey.github.io/api/matching/#include--exclude)是：

> If the string starts and ends with a slash (`/`), it will be compiled as a regular expression.

然后我删掉了多吉搜索 @include 规则结尾处的 `i`，然后重新访问多吉搜索即可正常运行。

因此在作者更新源代码前目前的解决办法有：

1. 修改脚本管理器中 AllSearch 源码中相关的 @include 规则；
2. 在脚本管理器中 AllSearch 设置界面中添加对应网站的匹配规则，如：`/^https?:\/\/www\.dogedoge\.com\/results\?q/`

其他与此相似的 @include 规则也可以这样处理。

@wolfan @endday

**Comment by SylleoYr** [comment]
另外百度的另一个搜索 url [https://www.baidu.com/baidu?wd=...](https://www.baidu.com/baidu?wd=...) 也无法显示工具栏，无论我是添加 @include 规则还是 @match 规则，都无法显示，不知道是不是我这边的问题。

**Comment by endday** [comment]
@SylleoYr 太感谢啦，第一次有热心的大佬直接帮我定位问题，十分感谢，多吉和百度另一个页面的问题以修复，请在greayfork更新版本

**Comment by wolfan** [comment]
@endday 啥时候会提供自定义搜索内容，比如咱不想要yandex，想加入naver，还想把DDG的排位提升下什么的。

**Comment by endday** [comment]
> @endday 啥时候会提供自定义搜索内容，比如咱不想要yandex，想加入naver，还想把DDG的排位提升下什么的。

正在做了，现在界面差不多了，但是还在考虑在保留自定义的顺序和网址的情况，如何合并插件的数据和用户的数据

**Comment by SylleoYr** [comment]
> 
> 
> @SylleoYr 太感谢啦，第一次有热心的大佬直接帮我定位问题，十分感谢，多吉和百度另一个页面的问题已经修复，请在[greasyfork](https://greasyfork.org/zh-CN/scripts/397993-all-search-%E5%85%A8%E6%90%9C-%E4%B8%80%E4%B8%AA%E6%90%9C%E7%B4%A2%E5%BC%95%E6%93%8E%E5%BF%AB%E6%8D%B7%E8%B7%B3%E8%BD%AC%E8%8F%9C%E5%8D%95)更新版本

哈哈，客气了，我也只是一只小白，初学者 😜

**Comment by Noah1995** [comment]
> > @endday啥时候会提供自定义搜索内容，某些咱不想要yandex，想加入naver，还想把DDG的排位提升下什么的。
> 
> 正在做好，现在界面差不多了，但是还在考虑在保留自定义的顺序和网址的情况下，如何合并插件的数据和用户的数据

快建个QQ群鸭...

**Comment by endday** [comment]
> > > @endday啥时候会提供自定义搜索内容，某些咱不想要yandex，想加入naver，还想把DDG的排位提升下什么的。
> > 
> > 
> > 正在做好，现在界面差不多了，但是还在考虑在保留自定义的顺序和网址的情况下，如何合并插件的数据和用户的数据
> 
> 快建个QQ群鸭...

148498263 来了来了
