### ISSUE TITLE
默认第一个，自定义显示内容，多个搜索引擎快速跳转

### ISSUE THREAD

**Issue by mr-dragon** [endday/all-search#8]
#### 默认第一个，自定义显示内容，多个搜索引擎快速跳转，不然意义不大了，希望完全复刻下searchEngineJump的2个功能：

![默认第一个，自定义显示内容，多个搜索引擎快速跳转，不然意义不大了，希望完全复刻下searchEngineJump的2个功能](https://user-images.githubusercontent.com/25114117/96394639-1a401880-11f5-11eb-9d70-dbb9bdd122d4.png)

**Comment by endday** [comment]
自定义设置的页面在做了，别急哈，你这个功能下次我也会安排上的
